blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/nouveauxterritoires/cal.nt/discussions
    about: Need help self-hosting or have a general question about Cal.nt? Open a discussion
